### ISSUE TITLE
bedgraphs not created when USE_BED_NAMES is True

### ISSUE THREAD

**Issue by byee4** [meracorley/f-SHAPE-eCLIP#1]
I created a dummy file for testing the pipeline outputs on line 369 of bedReactivities.py, but should be fixed to produce an actual bedfile:

https://github.com/meracorley/f-SHAPE-eCLIP/blob/e5683f8805e28b7c8c39c57caef1bf154a63f092/bedReactivities.py#L369

**Comment by meracorley** [comment]
Oh ummm, yeah the USE_BED_NAME option is misleading. It's purpose is to do
something a little more complicated than just using the bed name in the
output file. I should change how it's described in the help message.
*USE_BED_NAME should just be kept false for now...*

**Comment by byee4** [comment]
got it!
